---

# L3LS Fabric Values - update these values with caution, some changes could be disruptive.

fabric_name: DC1_FABRIC

# Point to Point Network Summary range, assigned as /31 for each uplink interfaces
# Assign range larger then total [ spines * total potential leafs * 2 ]
underlay_p2p_network_summary: 172.18.255.0/24

# IP address range for evpn loopback for all switches in fabric, assigned as /32s
# Assign range larger then total spines + total leafs switches


# VTEP VXLAN Tunnel source loopback IP for leaf switches, assigned in /32s
# Assign range larger then total leaf switches
vtep_loopback_ipv4_pool: 192.168.254.0/24

# mlag pair IP assignment - assign blocks - Assign range larger then total spines + total leafs switches
mlag_ips:
  leaf_peer_l3: 10.255.249.0/24
  mlag_peer: 10.255.250.0/24

# Enable vlan aware bundles
vxlan_vlan_aware_bundles: true

# bgp peer groups passwords
bgp_peer_groups:
  IPv4_UNDERLAY_PEERS:
    password: "AQQvKeimxJu+uGQ/yYvv9w=="
  EVPN_OVERLAY_PEERS:
      password: "q+VNViP5i4rVjW1cxFv2wA=="
  MLAG_IPv4_UNDERLAY_PEER:
      password: "vnEaG8gMeQf3d3cN6PktXQ=="

# Spine Switches
spine:
  defaults:
    platform: vEOS-LAB
    bgp_as: 65001
    loopback_ipv4_pool: 192.168.251.0/24
    bgp_defaults: ['no bgp default ipv4-unicast', 'distance bgp 20 200 200']
    leaf_as_range: 65101-65132
    mlag_peer_ipv4_pool: 10.255.252.0/24
    mlag_peer_l3_ipv4_pool: 10.255.251.0/24
  nodes:
    s1-spine1:
      id: 1
      mgmt_ip: 192.168.0.10/24
      mac_address: '00:1c:73:c0:c6:10'
    s1-spine2:
      id: 2
      mgmt_ip: 192.168.0.11/24
      mac_address: '00:1c:73:c0:c6:11'

# Leaf switch groups
# A maximum of two nodes can form a leaf group
# When two nodes are in a leaf group this will automatically form mlag pair

l3leaf:
  defaults:
    platform: vEOS-LAB
    bgp_as: 65100
    loopback_ipv4_pool: 192.168.255.0/24
    vtep_loopback_ipv4_pool: 192.168.254.0/24
    uplink_switches: ['s1-spine1', 's1-spine2']
    uplink_interfaces: ['Ethernet2', 'Ethernet3']
    mlag_interfaces: [ Ethernet1, Ethernet6 ]
    uplink_ipv4_pool: 172.18.255.0/24
    mlag_peer_ipv4_pool: 10.255.252.0/24
    mlag_peer_l3_ipv4_pool: 10.255.251.0/24
    spanning_tree_mode: mstp
    spanning_tree_priority: 4096
    virtual_router_mac_address : 00:dc:00:00:00:0a
    bgp_defaults: ['no bgp default ipv4-unicast', 'distance bgp 20 200 200']
  node_groups:
    DC1_LEAF1:
      bgp_as: 65101
      filter:
        tenants: [ all ]
        tags: [ web, app ]
      nodes:
        s1-leaf1:
          id: 11
          mgmt_ip: 192.168.0.12/24
          uplink_switch_interfaces: ['Ethernet2', 'Ethernet2']
          mac_address: '00:1c:73:c0:c6:12'
        s1-leaf2:
          id: 2
          mgmt_ip: 192.168.0.13/24
          uplink_switch_interfaces: ['Ethernet3', 'Ethernet3']
          mac_address: '00:1c:73:c0:c6:13'
    DC1_LEAF2:
      bgp_as: 65102
      filter:
        tenants: [ Tenant_A, Tenant_B, Tenant_C ]
        tags: [ opzone, web, app, db, vmotion, nfs ]
      nodes:
        s1-leaf3:
          id: 3
          mgmt_ip: 192.168.0.14/24
          uplink_switch_interfaces: ['Ethernet4', 'Ethernet4']
          mac_address: '00:1c:73:c0:c6:14'
        s1-leaf4:
          id: 4
          mgmt_ip: 192.168.0.15/24
          uplink_switch_interfaces: ['Ethernet5', 'Ethernet5']
          mac_address: '00:1c:73:c0:c6:15'

#### Override for vEOS Lab Caveats ####

# Disable update wait-for-convergence and update wait-for-install, which is not supported in vEOS-LAB.

spine_bgp_defaults:
#  - update wait-for-convergence
#  - update wait-install
  - no bgp default ipv4-unicast
  - distance bgp 20 200 200

leaf_bgp_defaults:
#  - update wait-install
  - no bgp default ipv4-unicast
  - distance bgp 20 200 200

# Upodate p2p mtu 9000 -> 1500
p2p_uplinks_mtu: 1500

# Adjust default bfd values
bfd_multihop:
  interval: 1200
  min_rx: 1200
  multiplier: 3

aaa_authorization:
   exec:
     default: local

## EVPN Host Flapping Settings
evpn_hostflap_detection:
  # If set to false it will disable EVPN host-flap detection
  enabled: true
  # Minimum number of MAC moves that indicate a MAC duplication issue
  threshold: 10
  # Time (in seconds) to detect a MAC duplication issue
  window: 180

event_handlers:
  evpn-blacklist-recovery:
    action_type: bash
    action: FastCli -p 15 -c "clear bgp evpn host-flap"
    delay: 300
    trigger: on-logging
    regex:  EVPN-3-BLACKLISTED_DUPLICATE_MAC
    asynchronous: true
aliases: |
  alias test2 show ip int brief
  alias test3 show ip int brief
  alias test4 show ip int brief
  alias test6 show ip int brief
