---

- name: validate states on EOS devices
  hosts: ATD_FABRIC
  connection: httpapi
  gather_facts: false
  tasks:
    - name: validate states on EOS devices
      tags: [validate]
      import_role:
         name: arista.avd.eos_validate_state
