---
- name: Cleanup CVP in default configuration
  hosts: cv_server
  connection: local
  tags: [deploy]
  gather_facts: no
  tasks:
    - name: run CVP provisioning
      import_role:
         name: arista.avd.eos_config_deploy_cvp
      vars:
        container_root: 'ATD_FABRIC'
        configlets_prefix: 'atd-avd'
        cv_collection: v3
        device_filter:
        - leaf
        - spine
        state: absent
        execute_tasks: true
