---
- name: Validate DC Fabric configuration with Batfish
  hosts: localhost
  connection: local
  roles:
    - batfish.base

  vars:
    snapshot: atd-target
    network: ATD
  tasks:

    - name: Pre Deployment fabric validation
      import_role:
         name: eos_pre_fabric_validation


