- hosts: all
  gather_facts: no
  tasks:
    - name: Gather command outputs from devices
      # collect show version and show ip interface brief
      arista.eos.eos_command:
        commands:
      register: switch_outputs
    - debug:
        var: switch_outputs
    - name: Create output directory
      delegate_to: localhost
      ansible.builtin.file: 
        path: "./outputs"
        state: directory
    - name: Write device output to file
      delegate_to: localhost
      ansible.builtin.copy: 
        content: # fill this out to pull JUST the command output collected above - replace \n with actual newlines
        dest:  # fill this out to create a file with outputs per device, named after the device, in the outputs/ directory