port_profiles:

  TENANT_A_B:
    mode: trunk
    vlans: "110-111,210-214"

  TENANT_A:
    mode: trunk
    vlans: "110"

  TENANT_B:
    mode: trunk
    vlans: "120-212"


servers:

  server01:
    rack: RackB
    adapters:
      - server_ports: [ Ethernet1, Ethernet2, Ethernet3, Ethernet4 ]
        switch_ports: [ Ethernet4, Ethernet5 ]
        switches: [ leaf1, leaf2 ]
        profile: TENANT_B
        port_channel:
          state: present
          description: PortChannel1
          mode: active

  server02:
    rack: RackB
    adapters:
      - server_ports: [ Ethernet1, Ethernet2, Ethernet3, Ethernet4  ]
        switch_ports: [ Ethernet4, Ethernet5 ]
        switches: [ leaf3, leaf4 ]
        profile: TENANT_B
        port_channel:
          state: present
          description: PortChannel1
          mode: active

