---
- name: Gather data from devices for customized banners
  hosts: eos
  gather_facts: no
  collections:
    - arista.eos
  tags:
    - configuration
  tasks:
    # Add tasks here to build your banners

- name: Deploy configlets and configlet mappings to CVP 
  hosts: cvp
  gather_facts: no
  connection: local
  collections:
    - arista.cvp
  tags:
    - deployment
    - cvp
  vars:
    provisioning_containers:
      S1:
        parentContainerName: Tenant
      S2:
        parentContainerName: Tenant 
      S1-Brdr: 
        parentContainerName: S1
      S1-Core: 
        parentContainerName: S1
      S1-Hosts: 
        parentContainerName: S1
      S1-Leaf: 
        parentContainerName: S1
      S1-Spine: 
        parentContainerName: S1
      S2-Brdr:
        parentContainerName: S2
      S2-Core:
        parentContainerName: S2
      S2-Hosts:
        parentContainerName: S2
      S2-Leaf:
        parentContainerName: S2
      S2-Spine:
        parentContainerName: S2
    configlets:
      # add additional configlet mappings as needed
      motd_banner: "{{ lookup('file', './configs/motd_banner.cfg') }}"
    managed_devices:
      - fqdn: s1-host1.atd.lab
        parentContainerName: S1-Hosts 
        configlets:
          # map configlets to your devices
      - fqdn: s1-host2.atd.lab
        parentContainerName: S1-Hosts 
        configlets:
          # map configlets to your devices'
      - fqdn: s1-leaf1.atd.lab
        parentContainerName: S1-Leaf 
        configlets: 
          # map configlets to your devices 
      - fqdn: s1-leaf2.atd.lab
        parentContainerName: S1-Leaf 
        configlets: 
          # map configlets to your devices
      - fqdn: s1-leaf3.atd.lab
        parentContainerName: S1-Leaf 
        configlets: 
          # map configlets to your devices
      - fqdn: s1-leaf4.atd.lab
        parentContainerName: S1-Leaf 
        configlets: 
          # map configlets to your devices
      - fqdn: s1-spine1.atd.lab
        parentContainerName: S1-Spine 
        configlets: 
          # map configlets to your devices
      - fqdn: s1-spine2.atd.lab
        parentContainerName: S1-Spine 
        configlets: 
          # map configlets to your devices
      - fqdn: s1-brdr1.atd.lab
        parentContainerName: S1-Brdr 
        configlets: 
          # map configlets to your devices
      - fqdn: s1-brdr2.atd.lab
        parentContainerName: S1-Brdr 
        configlets: 
          # map configlets to your devices
      - fqdn: s1-core1.atd.lab
        parentContainerName: S1-Core 
        configlets: 
          # map configlets to your devices
      - fqdn: s1-core2.atd.lab
        parentContainerName: S1-Core 
        configlets: 
          # map configlets to your devices
      - fqdn: s2-host1.atd.lab
        parentContainerName: S2-Hosts 
        configlets:
          # map configlets to your devices
      - fqdn: s2-host2.atd.lab
        parentContainerName: S2-Hosts 
        configlets:
          # map configlets to your devices'
      - fqdn: s2-leaf1.atd.lab
        parentContainerName: S2-Leaf 
        configlets: 
          # map configlets to your devices 
      - fqdn: s2-leaf2.atd.lab
        parentContainerName: S2-Leaf 
        configlets: 
          # map configlets to your devices
      - fqdn: s2-leaf3.atd.lab
        parentContainerName: S2-Leaf 
        configlets: 
          # map configlets to your devices
      - fqdn: s2-leaf4.atd.lab
        parentContainerName: S2-Leaf 
        configlets: 
          # map configlets to your devices
      - fqdn: s2-spine1.atd.lab
        parentContainerName: S2-Spine 
        configlets: 
          # map configlets to your devices
      - fqdn: s2-spine2.atd.lab
        parentContainerName: S2-Spine 
        configlets: 
          # map configlets to your devices
      - fqdn: s2-brdr1.atd.lab
        parentContainerName: S2-Brdr 
        configlets: 
          # map configlets to your devices
      - fqdn: s2-brdr2.atd.lab
        parentContainerName: S2-Brdr 
        configlets: 
          # map configlets to your devices
      - fqdn: s2-core1.atd.lab
        parentContainerName: S2-Core 
        configlets: 
          # map configlets to your devices
      - fqdn: s2-core2.atd.lab
        parentContainerName: S2-Core 
        configlets: 
          # map configlets to your devices
  tasks:
    - name: Collect facts from CVP 
      arista.cvp.cv_facts_v3:
      register: CVP_FACTS
    # - debug:
    #     var: CVP_FACTS
    - name: Build provisioning containers in CVP 
      arista.cvp.cv_container_v3:
        topology: "{{ provisioning_containers }}"
        apply_mode: loose
    - name: Load configlets into CVP 
      arista.cvp.cv_configlet_v3:
        configlets: "{{ configlets }}"
        configlets_notes: "Configlet managed by Ansible, created in TAC training lab"
    - name: Map configlets to devices
      arista.cvp.cv_device_v3:
        devices: "{{ managed_devices }}"
        state: present
        apply_mode: loose
        search_key: fqdn 
      register: CVP_DEVICES