ansible_httpapi_host: 192.168.0.5
ansible_host: 192.168.0.5
ansible_connection: httpapi
ansible_httpapi_use_ssl: True
ansible_httpapi_validate_certs: False
ansible_user: arista
ansible_password: # YOUR PASSWORD HERE
ansible_network_os: eos
ansible_httpapi_port: 443
ansible_python_interpreter: $(which python3)